// <auto-generated />
using GameDatabase.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameDatabase.Migrations
{
    [DbContext(typeof(PlayerContext))]
    [Migration("20250811122855_DbCreated")]
    partial class DbCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameDatabase.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("KD")
                        .HasColumnType("real");

                    b.Property<int>("accuracy")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("headshots")
                        .HasColumnType("int");

                    b.Property<int>("kills")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rank")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KD = 0.6f,
                            accuracy = 53,
                            email = "abc@gmail.com",
                            headshots = 9,
                            kills = 78,
                            password = "abc123",
                            rank = 2,
                            username = "abc"
                        },
                        new
                        {
                            Id = 2,
                            KD = 0.79f,
                            accuracy = 75,
                            email = "something@gmail.com",
                            headshots = 21,
                            kills = 190,
                            password = "iqjifnqw3",
                            rank = 3,
                            username = "xingq"
                        },
                        new
                        {
                            Id = 3,
                            KD = 0.95f,
                            accuracy = 80,
                            email = "ice23@gmail.com",
                            headshots = 89,
                            kills = 294,
                            password = "jr3i214",
                            rank = 4,
                            username = "matt41"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
