// <auto-generated />
using GameDatabase.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameDatabase.Migrations
{
    [DbContext(typeof(PlayerContext))]
    [Migration("20250821101131_dbCreated")]
    partial class dbCreated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameDatabase.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Accuracy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Headshots")
                        .HasColumnType("int");

                    b.Property<float>("KD")
                        .HasColumnType("real");

                    b.Property<int>("Kills")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accuracy = 53,
                            Email = "abc@gmail.com",
                            Headshots = 9,
                            KD = 0.6f,
                            Kills = 78,
                            Rank = 2,
                            Username = "abc"
                        },
                        new
                        {
                            Id = 2,
                            Accuracy = 75,
                            Email = "something@gmail.com",
                            Headshots = 21,
                            KD = 0.79f,
                            Kills = 190,
                            Rank = 3,
                            Username = "xingq"
                        },
                        new
                        {
                            Id = 3,
                            Accuracy = 80,
                            Email = "matt@gmail.com",
                            Headshots = 89,
                            KD = 0.95f,
                            Kills = 294,
                            Rank = 4,
                            Username = "matt41"
                        },
                        new
                        {
                            Id = 4,
                            Accuracy = 81,
                            Email = "user3@gmail.com",
                            Headshots = 90,
                            KD = 0.98f,
                            Kills = 456,
                            Rank = 6,
                            Username = "user39"
                        },
                        new
                        {
                            Id = 5,
                            Accuracy = 66,
                            Email = "bot@gmail.com",
                            Headshots = 2,
                            KD = 0.5f,
                            Kills = 34,
                            Rank = 1,
                            Username = "bot"
                        },
                        new
                        {
                            Id = 6,
                            Accuracy = 76,
                            Email = "bee33@gmail.com",
                            Headshots = 6,
                            KD = 0.85f,
                            Kills = 60,
                            Rank = 2,
                            Username = "bee3"
                        },
                        new
                        {
                            Id = 7,
                            Accuracy = 67,
                            Email = "newuser@gmail.com",
                            Headshots = 3,
                            KD = 0.7f,
                            Kills = 56,
                            Rank = 1,
                            Username = "player213"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
